<script setup></script>

<template>
  <div class="main_screen_view">
    <div class="main_container">
      <h1>Terms and Conditions</h1>
      <p><strong>Effective Date:</strong> 27th May, 2025</p>
      <p>Welcome to <strong>Bart Bong</strong>!</p>
      <p>
        These Terms and Conditions ("Terms") govern your use of the Bart Bong
        web application ("Bart Bong", "we", "us", or "our"). By accessing or
        using Bart Bong, you agree to be bound by these Terms. If you do not
        agree, do not use our services.
      </p>

      <h2>1. Description of Service</h2>
      <p>
        Bart Bong is an AI-powered platform that allows users to ask questions
        and receive AI-generated responses. The information provided is
        generated by artificial intelligence and is intended for informational
        and entertainment purposes only.
      </p>

      <h2>2. User Responsibilities</h2>
      <p>By using Bart Bong, you agree to:</p>
      <ul>
        <li>Use the service only for lawful purposes.</li>
        <li>
          Not use the service to create or distribute content that is harmful,
          offensive, abusive, defamatory, or violates any law.
        </li>
        <li>
          Not attempt to reverse-engineer, duplicate, or interfere with the
          functionality of the service.
        </li>
        <li>Be responsible for the content you input into the platform.</li>
      </ul>

      <h2>3. Content Disclaimer</h2>
      <ul>
        <li>
          Bart Bong uses machine learning to generate responses. These responses
          may occasionally be inaccurate, misleading, or inappropriate.
        </li>
        <li>
          Bart Bong does <strong>not</strong> provide professional advice (e.g.,
          medical, legal, financial). Always consult a qualified professional
          before making decisions based on the content generated.
        </li>
        <li>
          We do not guarantee the accuracy, completeness, or usefulness of any
          information provided by Bart Bong.
        </li>
      </ul>

      <h2>4. Account Usage (If Applicable)</h2>
      <ul>
        <li>
          You must provide accurate and complete information during sign-up.
        </li>
        <li>
          You are responsible for maintaining the confidentiality of your login
          credentials.
        </li>
        <li>
          You are responsible for all activities that occur under your account.
        </li>
      </ul>

      <h2>5. Privacy</h2>
      <p>
        Your use of Bart Bong is subject to our <a href="#">Privacy Policy</a>,
        which outlines how we collect, use, and protect your personal data.
      </p>

      <h2>6. Intellectual Property</h2>
      <p>
        All content, design, features, and functionality of Bart Bong (excluding
        user input) are the property of Bart Bong and are protected by
        copyright, trademark, and other applicable laws.
      </p>

      <h2>7. Limitation of Liability</h2>
      <p>To the maximum extent permitted by law:</p>
      <ul>
        <li>Bart Bong is provided "as is" and "as available."</li>
        <li>
          We make no warranties regarding the performance, accuracy, or
          reliability of the service.
        </li>
        <li>
          We are not liable for any damages arising from your use of the
          platform.
        </li>
      </ul>

      <h2>8. Modifications to the Service</h2>
      <p>
        We may modify or discontinue Bart Bong, temporarily or permanently, at
        any time without notice. We are not liable for any such modifications or
        discontinuation.
      </p>

      <h2>9. Termination</h2>
      <p>
        We may terminate or suspend your access to Bart Bong at any time,
        without prior notice or liability, for any reason including if you
        breach these Terms.
      </p>

      <h2>10. Governing Law</h2>
      <p>
        These Terms are governed by and construed in accordance with the laws of
        [Your Country or State], without regard to its conflict of law
        principles.
      </p>

      <h2>11. Changes to Terms</h2>
      <p>
        We reserve the right to update these Terms at any time. Changes will be
        effective immediately upon posting. Your continued use of Bart Bong
        constitutes your acceptance of the new Terms.
      </p>

      <h2>12. Contact Us</h2>
      <p style="padding-bottom: 50px">
        If you have any questions about these Terms, please contact us at:
        <a href="mailto:[contact@bartbong.com]">contact@bartbong.com</a>
      </p>
    </div>
  </div>
</template>

<style scoped>
a {
  color: #007aff;
}
.main_screen_view {
  position: absolute;
  top: 0px;
  left: 0px;
  right: 0px;
  bottom: 0px;
  display: flex;
  justify-content: center;
  overflow-y: auto;
}
.main_container {
  width: 100%;
  padding: 20px;
  max-width: 600px;
  color: white;
  box-sizing: border-box;
}
</style>
